CodePractice/Python/WordCloudSite/WCProgram/urls.py
#ここは下のURLconf

from django.urls import path

from . import views  # WCProgram's views(controller)
from . import DCdata  # WCProgram's views(controller)

from django.conf import settings
from django.conf.urls.static import static

app_name = 'WCProgram'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('kr/', views.kr, name = 'kr'),  # Basic kr
    path('jp/', views.jp, name = 'jp'),  # Basic jp
    path('en/', views.en, name = 'en'),  # Basic en
    path('GetWordCloud/', views.GetWordCloud, name = 'GWC'),   # Basic Code
    path('imageset', views.upload_file, name = 'upload'),   # / 入るとイメージのロードができない。

    path('DCData/', DCdata.DCDataTemplate, name ='DCD'),   # DCdata
    path('GetDCdata/', DCdata.GetDCWordCloud, name = 'GDWC'),   # Get DC Data Code
    path('DCimageset', DCdata.upload_file, name = 'DCupload'),   # / 入るとイメージのロードができない。
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CodePractice/Python/WordCloudSite/WordCloudSite/urls.py
#ここは一番上のURLconf

"""WordCloudSite URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('WordCloud/', include('WCProgram.urls')),  # 下appのURL追加
]

CodePractice/Python/WordCloudSite/WCProgram/models.py
from django.db import models

# title과 upload할 file에 대한 정보를 갖는 model
# file은 존재하지 않는 경우도 있으므로 null=True로 설정함
class UploadFileModel(models.Model):
    # models.FileField : 파일 저장을 지원하는 모델 필드
    # models.ImageField : 이미지 저장을 지원하는 모델 필드(FileField 상속)

    #title = models.TextField(default='')
    file = models.FileField(null=True)
    #photo = models.ImageField(blank=True)

CodePractice/Python/WordCloudSite/WCProgram/forms.py
# UploadFileModel에 대한 modelform을 생성한다.

from django import forms

from .models import UploadFileModel

class UploadFileForm(forms.ModelForm):
    file = forms.FileField(
        label = 'Select a file',
        help_text= 'max. 42 megabytes'
    )

CodePractice/Python/WordCloudSite/WCProgram/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse

# World Cloud Package
from konlpy.tag import Twitter; t = Twitter()
from wordcloud import WordCloud
from wordcloud import STOPWORDS
from wordcloud import ImageColorGenerator
from PIL import Image
import jpype

# Web Page Scripting Package
from bs4 import BeautifulSoup
import requests as rq  # request

# Data Package
import numpy as np
import matplotlib.pyplot as plt
import gc

# Language Package
import nltk  # Natural Language(자연어) tool kit(도구 모음)

# Python Debugger
import pdb

# Download
import io

# Japanese
import MeCab

# File Upload
from django.conf import settings
from django.core.files.storage import FileSystemStorage  # model안쓰고 가볍게 업로드 할 때 사용

def index(request):
    context = {
        '': ""
    }
    return render(request, 'WCProgram/index.html', context)
    # request, template(loader), value(context = dict系)

def kr(request):
    context = {
        '': ""
    }
    return render(request, 'WCProgram/kr.html', context)

def jp(request):
    context = {
        '': ""
    }
    return render(request, 'WCProgram/jp.html', context)

def en(request):
    context = {
        '': ""
    }
    return render(request, 'WCProgram/en.html', context)

def mecab_analysis(text):
    jt = MeCab.Tagger('-Ochasen')
    jt.parse('-Ochasen')  # これ重要！！！！
    node = jt.parseToNode(text)
    output = []
    while (node):
        if node.surface != "":  # ヘッダとフッタを除外
            word_type = node.feature.split(",")[0]
            if word_type in ["形容詞", "動詞", "名詞", "副詞"]:
                output.append(node.surface)
        node = node.next
        if node is None:
            break
    return output

def GetWordCloud(request):  # post처리가 일어나는곳. -> Redirct처리(CSRF보안에러 일어날수도 있음), matplotlib's Tkinter always use main thread
    check = request.POST['lang']
    image = request.POST['image']
    URL = request.POST['address']
    user_agent = 'forget'
    overloadText = ""
    response = rq.get(URL, headers={'User-Agent': user_agent})
    soup = BeautifulSoup(response.text, 'html.parser')  # 전체 HTML에서 특정 부분만 찾기 위한 html parsing

    if image != "":
        mask = np.array(Image.open(image))  # select mask
        image_colors = ImageColorGenerator(mask)
    else:
        mask = np.array(Image.open("WCProgram/static/WCProgram/images/oval.jpg"))  # default mask

    alldata = soup.find_all()
    taglist = set()

    # get all tags(どんなサイトでもデータを習得)
    for tag in alldata:
        taglist.add(tag.name)

    if(check == 'kr'):
        # 사용자를 대신하여 일을 수행하는 소프트웨어 에이전트, get방식으로 값을 가져왔는데 내용이 안보이면 header에 User-Agent 아무값이나 넣어보자

        Article = soup.findAll(taglist)  # multiple tag

        for index in Article:
            overloadText = overloadText + index.text + " "

        # For [No core dump will be written] Exception Clear
        if jpype.isJVMStarted():
            jpype.attachThreadToJVM()

        tokens_ko = t.nouns(overloadText)  # konlpy Package의 t를 이용하여 단어 나눔

        stop_words = ['거', '왜', '좀', '레', '뭐', '임', '코', '페', '타', '함', '요', '이', '어', '온', '내']  # Excepted Wrods
        tokens_ko = [each_word for each_word in tokens_ko if
                     each_word not in stop_words]  # for, if, not in 이용해서 제외단어 이외의 단어만 남김
        ko = nltk.Text(tokens_ko, name='갤DB')

        data = ko.vocab().most_common(500)  # 정렬된 list-tuple형식으로 변경(Count해줌. 최대 500)
        tmp_data = dict(data)  # dict형식으로 데이터 변경

        # in Mac
        wc = WordCloud(font_path="/Library/Fonts/AppleGothic.ttf",
                       mask=mask, stopwords=stop_words, min_font_size=5, max_words=2000,
                       background_color="white").generate_from_frequencies(tmp_data)

        # in Ubuntu - 한글
        # wc = WordCloud(font_path="/usr/share/fonts/truetype/nanum/NanumBarunGothic.ttf",
        #               mask=mask, min_font_size=5, max_words=2000, background_color="white").generate_from_frequencies(tmp_data)

    elif(check == 'jp'):
        Article = soup.findAll(taglist)  # 닉네임 전부 가져옴

        for index in Article:
            overloadText = overloadText + index.text

        tokens_jp = mecab_analysis(overloadText)  # konlpy Package의 t를 이용하여 단어 나눔, "形容詞", "動詞","名詞", "副詞"만 필요
        jp = nltk.Text(tokens_jp, name='杏')  # 중복 제거를 위해 token형식으로 만듬
        data = jp.vocab().most_common(500)  # 정렬된 list-tuple형식으로 변경(Count해줌. 최대 500)(
        tmp_data = dict(data)  # dict형식으로 데이터 변경

        stop_words = ['てる', 'いる', 'なる', 'れる', 'する', 'ある', 'こと', 'これ', 'さん', 'して',
                      'くれる', 'やる', 'くださる', 'そう', 'せる', 'した', '思う',
                      'それ', 'ここ', 'ちゃん', 'くん', '', 'て', 'に', 'を', 'は', 'の', 'が', 'と', 'た', 'し', 'で',
                      'ない', 'も', 'な', 'い', 'か', 'ので', 'よう', '[', ']', '/']
        # Python 3.0부턴 유니코드 표현을 위해 앞에 u를 붙일 필요가 없음(이미 유니코드로 표현되므로)

        # in Max
        wc = WordCloud(font_path="/Library/Fonts/Hannari.otf",
                       mask=mask, stopwords=stop_words, max_words=2000,
                       background_color='white').generate_from_frequencies(tmp_data)

        # in Ubuntu - 日本語
        # wc = WordCloud(font_path="/usr/share/fonts/truetype/fonts-japanese-gothic.ttf",
        #               mask=mask, min_font_size=5, max_words=2000, background_color="white").generate_from_frequencies(tmp_data)

    elif(check == 'en'):
        Article = soup.findAll(taglist)

        for index in Article:
            overloadText = overloadText + index.text

        text = overloadText

        stopwords = set(STOPWORDS)  # Use STOPWORDS Class
        stopwords.add("int")
        stopwords.add("ext")

        # English Don't need font check
        wc = WordCloud(mask=mask, stopwords=stopwords, max_words=2000,
                       background_color='white').generate(text)

    # killed error：ラムが足りないときによく発動
    plt.figure(figsize=(16, 16))

    if image != "":
        plt.imshow(wc.recolor(color_func=image_colors), interpolation='bilinear')
    else:
        plt.imshow(wc, interpolation="bilinear")

    plt.axis("off")
    #plt.savefig('GalleryDataWC.png')  # word cloud 세이브

    buf = io.BytesIO()
    plt.savefig(buf, format='png')

    del mask
    plt.clf()
    plt.close()  # If you don't close, you can see a lot of error
    response.close()

    response = HttpResponse(buf.getvalue(), content_type='image/png')  # これままでは、イメージがWeb画面に見せるだけです。
    response['Content-Disposition'] = "attachment; filename=picture.png"  # Downloadまでするコード
    #response = HttpResponseRedirect(reverse('WCProgram:index'))

    buf.close()
    Article.clear()
    gc.collect()  # garbage collect empty(for server memory)

    return response

def upload_file(request):
    lang = request.POST['lang']
    if request.method == "POST" and request.FILES.get('myfile', False): # POST값을 받음, 선택된게 아무것도 없을경우 아무것도 없음을 반환
        myfile = request.FILES['myfile']
        fs = FileSystemStorage()
        filename = fs.save(myfile.name, myfile)
        upload_file_url = fs.url(filename)[1:] #substring
        return render(request, 'WCProgram/'+lang+'.html', {'uploaded_file_url':upload_file_url})
        #return HttpResponseRedirect(reverse('WCProgram:en'))
        # 모델까지 추가할시, Redirect로 파일에 돌아가서 모델을 통해 데이터를 불러와서 사용 하는듯(이미지 URL이라던가)
        # 새로고침시 재처리를 방지하려면 위 방식(Redirect)을 써야함.
    return render(request, 'WCProgram/'+lang+'.html')

CodePractice/Python/WordCloudSite/WCProgram/templates/WCProgram/DCDataTemplate.html
<!DOCTYPE html>

<!--
    180614
    Word Cloud Export System Prototype
    by jhkim
-->

{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=0.8"> <!-- モバイル画面にも合わせて設定 -->
    <script src="https://code.jquery.com/jquery-2.2.3.min.js"></script>  <!-- JQuery -->
    <link rel="stylesheet" type="text/css" href="{% static 'WCProgram/style.css' %}" />
    <title>GetWordCloud!</title>
</head>
<body>
    <div id="loading">
        <img id="loading-image" src="{% static 'WCProgram/images/Loading.gif' %}" alt="Loading..." />
        <h1>작업중입니다...</h1>
        <p>다운로드 후 다시 출력을 하고싶으면 페이지를 새로고침 해주세요</p>
    </div>

    <h1>갤러리와 페이지를 선택하세요</h1>
    <!-- if you want new tap page, Do like this : <form target="_blank" ...>-->
    <form id="submitform" action="{% url 'WCProgram:GDWC' %}" method="post">   {# url [APPNAME]:[URLNAME], urls.pyでAPP名前の設定が必要 #}
        {% csrf_token %} <!-- Cross Site Request Forgery(CSRF)防止-->
        <div class="simple">
            <input type="hidden" id="address" name="address" value="http://gall.dcinside.com/"></input>

            <!--============================ Gallery List ============================-->
            <select class="gallery" name="gallery">
                <option value="board/lists/?id=tree">식물 갤러리</option>
                <option value="board/lists/?id=idolmaster">아이돌마스터 갤러리</option>
                <option value="board/lists/?id=leagueoflegends2">리그 오브 레전드 갤러리</option>
                <option value="mgallery/board/lists/?id=aoegame">중세게임 마이너 갤러리</option>
                <option value="board/lists/?id=baseball_new7">국내야구 갤러리</option>
                <option value="board/lists/?id=comic_new1">만화 갤러리</option>
            </select>

            <!--============================ Start Page ============================-->
            <select class="spage" name="spage">
                {# 정말 불행히도, Django Template언어에선 range를 제공하지 않음.
                   그래서 아래와 같은 편법을 쓰거나, response(혹은 render)로 Python에서 만든 range 값을 가져와서 써야함 #}
                {% for i in "x"|rjust:"1000" %}
                <option value={{ forloop.counter }}>{{ forloop.counter }} ~</option>
                {% endfor %}
            </select>

            <!--============================ End Page ============================-->
            <select class="epage" name="epage">
                {% for i in "x"|rjust:"1000" %}
                <option value={{ forloop.counter }}>{{ forloop.counter }}</option>
                {% endfor %}
            </select>

            <!--============================ Subject ============================-->
            <select class="WorN" name="WorN">
                <option value="W">글 데이터</option>
                <option value="N">닉네임 데이터</option>
            </select>
            <input type="submit" id="Dobutton" value="출력"></input>
            <input type="hidden" name="image" value="{{ uploaded_file_url }}"></input> <!-- 이미지 파일 -->
        </div>
    </form>

    <!-- Upload Test, upload하기 위해서는 form에 enctype="multipart/form-data"설정이 필요함, novalidate는 form제출시 유효성 검사를 하지 않게 해줌. -->
    <form id="uploadform" method="post" action="{% url 'WCProgram:DCupload' %}" enctype="multipart/form-data" novalidate>
        {% csrf_token %} <!-- Cross Site Request Forgery(CSRF)防止(Form안에 꼭 필요)-->
        <div class="upload">
            <input type="file" name="myfile">
            <input type="submit" value="Upload"></input>
        </div>
    </form>

    <div class="Selected">
        {% if uploaded_file_url == null %} <!-- null check -->
        <h2>No images selected</h2>
        {% else %}
        <!-- Upload된 파일은 file의 url을 href로 지정하고 download를 넣어주면 다운 가능 -->
        <h2>This is your Selected image</h2>
        <img src="{{ uploaded_file_url }}" width="640px" height="480px" alt="SelectImage" />
        {% endif %}
    </div>
</body>

<script>
    // 일단 새로고침 하라고 창 띄우는 간편한 방식으로 진행
    // 다중 submit제한.
    $("#loading").hide();

    $('#submitform').submit(function(e) {
       $("#loading").show();
    });

    $('#uploadform').submit(function(e) {
    });
</script>

</html>

CodePractice/Python/WordCloudSite/WCProgram/templates/WCProgram/en.html
<!DOCTYPE html>

<!--
    180614
    Word Cloud Export System Prototype
    by jhkim
-->

{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=0.8"> <!-- モバイル画面にも合わせて設定 -->
    <script src="https://code.jquery.com/jquery-2.2.3.min.js"></script>  <!-- JQuery -->
    <link rel="stylesheet" type="text/css" href="{% static 'WCProgram/style.css' %}" />
    <title>GetWordCloud!</title>
</head>
<body>
    <div id="loading">
      <img id="loading-image" src="{% static 'WCProgram/images/Loading.gif' %}" alt="Loading..." />
      <p>Export and Downloading...</p>
      <p>If you want to do it again, please refresh</p>
    </div>

    <h1>Get your Word Cloud!</h1>
    <!-- if you want new tap page, Do like this : <form target="_blank" ...>-->
    <form id="submitform" action="{% url 'WCProgram:GWC' %}" method="post">   {# url [APPNAME]:[URLNAME], urls.pyでAPP名前の設定が必要 #}
        {% csrf_token %} <!-- Cross Site Request Forgery(CSRF)防止-->
        <div class="simple">
            <input type="text" id="address" name="address" placeholder="Input Site Address!!"></input>
            <input type="submit" id="Dobutton" value="Export"></input>
            <input type="hidden" name="lang" value="en"></input>
            <input type="hidden" name="image" value="{{ uploaded_file_url }}"></input> <!-- 이미지 파일 -->
        </div>
    </form>

    <!-- Upload Test, upload하기 위해서는 form에 enctype="multipart/form-data"설정이 필요함, novalidate는 form제출시 유효성 검사를 하지 않게 해줌. -->
    <form id="uploadform" method="post" action="{% url 'WCProgram:upload' %}" enctype="multipart/form-data" novalidate>
        {% csrf_token %} <!-- Cross Site Request Forgery(CSRF)防止(Form안에 꼭 필요)-->
        <div class="upload">
            <input type="file" name="myfile">
            <input type="submit" value="Upload"></input>
            <input type="hidden" name="lang" value="en"></input>
        </div>
    </form>

    <div class="Selected">
        {% if uploaded_file_url == null %} <!-- null check -->
        <h2>No images selected</h2>
        {% else %}
        <!-- Upload된 파일은 file의 url을 href로 지정하고 download를 넣어주면 다운 가능 -->
        <h2>This is your Selected image</h2>
        <img src="{{ uploaded_file_url }}" width="640px" height="480px" alt="SelectImage" />
        {% endif %}
    </div>
</body>

<script>
     $("#loading").hide();

     $('#submitform').submit(function(e) {
        $("#loading").show();
     });

     $('#uploadform').submit(function(e) {
     });
</script>

</html>

CodePractice/Python/WordCloudSite/WCProgram/templates/WCProgram/jp.html
<!DOCTYPE html>

<!--
    180614
    Word Cloud Export System Prototype
    by jhkim
-->

{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=0.8"> <!-- モバイル画面にも合わせて設定 -->
    <script src="https://code.jquery.com/jquery-2.2.3.min.js"></script>  <!-- JQuery -->
    <link rel="stylesheet" type="text/css" href="{% static 'WCProgram/style.css' %}" />
    <title>GetWordCloud!</title>
</head>
<body>
    <div id="loading">
      <img id="loading-image" src="{% static 'WCProgram/images/Loading.gif' %}" alt="Loading..." />
      <p>作業中です・・・</p>
      <p>再びやりたいならリフレッシュしてください。</p>
    </div>

    <h1>あなただけのワードクラウドを貰いましょう!</h1>
    <!-- if you want new tap page, Do like this : <form target="_blank" ...>-->
    <form id="submitform" action="{% url 'WCProgram:GWC' %}" method="post">   {# url [APPNAME]:[URLNAME], urls.pyでAPP名前の設定が必要 #}
        {% csrf_token %} <!-- Cross Site Request Forgery(CSRF)防止-->
        <div class="simple">
            <input type="text" id="address" name="address" placeholder="ここにサイトの住所を入れてください!!"></input>
            <input type="submit" id="Dobutton" value="出力"></input>
            <input type="hidden" name="lang" value="jp"></input>
            <input type="hidden" name="image" value="{{ uploaded_file_url }}"></input> <!-- 이미지 파일 -->
        </div>
    </form>

    <!-- Upload Test, upload하기 위해서는 form에 enctype="multipart/form-data"설정이 필요함, novalidate는 form제출시 유효성 검사를 하지 않게 해줌. -->
    <form id="uploadform" method="post" action="{% url 'WCProgram:upload' %}" enctype="multipart/form-data" novalidate>
        {% csrf_token %} <!-- Cross Site Request Forgery(CSRF)防止(Form안에 꼭 필요)-->
        <div class="upload">
            <input type="file" name="myfile">
            <input type="submit" value="Upload"></input>
            <input type="hidden" name="lang" value="jp"></input>
        </div>
    </form>

    <div class="Selected">
        {% if uploaded_file_url == null %} <!-- null check -->
        <h2>選択された画像がありません</h2>
        {% else %}
        <!-- Upload된 파일은 file의 url을 href로 지정하고 download를 넣어주면 다운 가능 -->
        <h2>画像を選択しました。この画像で出力されます。</h2>
        <img src="{{ uploaded_file_url }}" width="640px" height="480px" alt="SelectImage" />
        {% endif %}
    </div>
</body>

<script>
    $("#loading").hide();

    $('#submitform').submit(function(e) {
       $("#loading").show();
    });
</script>

</html>

CodePractice/Python/WordCloudSite/WCProgram/templates/WCProgram/kr.html
<!DOCTYPE html>

<!--
    180614
    Word Cloud Export System Prototype
    by jhkim
-->

{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=0.8"> <!-- モバイル画面にも合わせて設定 -->
    <script src="https://code.jquery.com/jquery-2.2.3.min.js"></script>  <!-- JQuery -->
    <link rel="stylesheet" type="text/css" href="{% static 'WCProgram/style.css' %}" />
    <title>GetWordCloud!</title>
</head>
<body>
    <div id="loading">
        <img id="loading-image" src="{% static 'WCProgram/images/Loading.gif' %}" alt="Loading..." />
        <h1>작업중입니다...</h1>
        <p>다운로드 후 다시 출력을 하고싶으면 페이지를 새로고침 해주세요</p>
    </div>

    <h1>당신만의 워드 클라우드를 출력하세요!</h1>
    <!-- if you want new tap page, Do like this : <form target="_blank" ...>-->
    <form id="submitform" action="{% url 'WCProgram:GWC' %}" method="post">   {# url [APPNAME]:[URLNAME], urls.pyでAPP名前の設定が必要 #}
        {% csrf_token %} <!-- Cross Site Request Forgery(CSRF)防止-->
        <div class="simple">
            <input type="text" id="address" name="address" placeholder="이곳에 사이트 주소를 입력하세요!!"></input>
            <input type="submit" id="Dobutton" value="출력"></input>
            <input type="hidden" name="lang" value="kr"></input>
            <input type="hidden" name="image" value="{{ uploaded_file_url }}"></input> <!-- 이미지 파일 -->
        </div>
    </form>

    <!-- Upload Test, upload하기 위해서는 form에 enctype="multipart/form-data"설정이 필요함, novalidate는 form제출시 유효성 검사를 하지 않게 해줌. -->
    <form id="uploadform" method="post" action="{% url 'WCProgram:upload' %}" enctype="multipart/form-data" novalidate>
        {% csrf_token %} <!-- Cross Site Request Forgery(CSRF)防止(Form안에 꼭 필요)-->
        <div class="upload">
            <input type="file" name="myfile">
            <input type="submit" value="Upload"></input>
            <input type="hidden" name="lang" value="kr"></input>
        </div>
    </form>

    <div class="Selected">
        {% if uploaded_file_url == null %} <!-- null check -->
        <h2>선택된 이미지가 없습니다.</h2>
        {% else %}
        <!-- Upload된 파일은 file의 url을 href로 지정하고 download를 넣어주면 다운 가능 -->
        <h2>이미지를 선택했습니다. 이 이미지로 출력됩니다.</h2>
        <img src="{{ uploaded_file_url }}" width="640px" height="480px" alt="SelectImage" />
        {% endif %}
    </div>
</body>

<script>
    $("#loading").hide();

    $('#submitform').submit(function(e) {
       $("#loading").show();
    });
</script>

</html>